"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, Plus, Search, X } from "lucide-react";
import { notFound } from "next/navigation";

type RecordItem = { id: number; name: string; detail: string; owner: string; status: string; createdAt: string };
type ModuleConfig = { eyebrow: string; title: string; description: string; entity: string; action: string; nameLabel: string; detailLabel: string; detailPlaceholder: string; statuses: string[]; seeds: RecordItem[] };
const configs: Record<string, ModuleConfig> = {
  crm: { eyebrow: "COMERCIAL", title: "CRM", description: "Relacionamentos, oportunidades e próximas ações em um só contexto.", entity: "oportunidade", action: "Nova oportunidade", nameLabel: "Oportunidade", detailLabel: "Valor estimado", detailPlaceholder: "R$ 25.000", statuses: ["Qualificação", "Diagnóstico", "Proposta", "Negociação"], seeds: [{ id: 1, name: "Portal comercial ACME", detail: "R$ 32.000", owner: "Caio", status: "Proposta", createdAt: "Hoje" }] },
  agenda: { eyebrow: "COMERCIAL", title: "Agenda", description: "Compromissos e próximas ações da equipe comercial.", entity: "compromisso", action: "Novo compromisso", nameLabel: "Assunto", detailLabel: "Data e horário", detailPlaceholder: "15/09 às 14:00", statuses: ["Planejado", "Confirmado", "Realizado"], seeds: [{ id: 1, name: "Diagnóstico com Cooperativa Oeste", detail: "Hoje às 14:00", owner: "Caio", status: "Confirmado", createdAt: "Hoje" }] },
  clientes: { eyebrow: "OPERAÇÃO", title: "Clientes", description: "Visão única de contas, contatos, projetos e histórico financeiro.", entity: "cliente", action: "Novo cliente", nameLabel: "Empresa", detailLabel: "Segmento", detailPlaceholder: "Agronegócio", statuses: ["Prospect", "Ativo", "Inativo"], seeds: [{ id: 1, name: "Santé Agrícola", detail: "Tecnologia agrícola", owner: "Marina", status: "Ativo", createdAt: "08 set" }] },
  equipe: { eyebrow: "OPERAÇÃO", title: "Equipe", description: "Capacidade, alocação e exceções que exigem ação.", entity: "pessoa", action: "Convidar pessoa", nameLabel: "Nome completo", detailLabel: "Cargo", detailPlaceholder: "Gerente de projetos", statuses: ["Ativo", "Férias", "Indisponível"], seeds: [{ id: 1, name: "Marina Souza", detail: "Gerente de projetos", owner: "Operação", status: "Ativo", createdAt: "01 set" }] },
  financeiro: { eyebrow: "FINANCEIRO", title: "Visão financeira", description: "Caixa, recebíveis, pagamentos e resultado gerencial.", entity: "lançamento", action: "Novo lançamento", nameLabel: "Descrição", detailLabel: "Valor", detailPlaceholder: "R$ 1.500", statuses: ["Previsto", "Aberto", "Pago", "Vencido"], seeds: [{ id: 1, name: "Parcela Portal Santé", detail: "R$ 8.400", owner: "Financeiro", status: "Aberto", createdAt: "10 set" }] },
  indicadores: { eyebrow: "GESTÃO", title: "Indicadores", description: "Dados conectados para entender causas e tomar decisões.", entity: "indicador", action: "Novo indicador", nameLabel: "Indicador", detailLabel: "Meta", detailPlaceholder: "85%", statuses: ["Saudável", "Atenção", "Crítico"], seeds: [{ id: 1, name: "Entregas no prazo", detail: "Meta 90%", owner: "Direção", status: "Atenção", createdAt: "Mensal" }] },
  copiloto: { eyebrow: "INTELIGÊNCIA", title: "Copiloto", description: "Perguntas e análises baseadas nos dados permitidos da organização.", entity: "pergunta", action: "Nova análise", nameLabel: "Pergunta", detailLabel: "Contexto", detailPlaceholder: "Projetos e financeiro", statuses: ["Pendente", "Analisando", "Concluída"], seeds: [{ id: 1, name: "Quais projetos precisam de atenção?", detail: "Portfólio atual", owner: "Jefferson", status: "Concluída", createdAt: "Hoje" }] },
  configuracoes: { eyebrow: "ADMINISTRAÇÃO", title: "Configurações", description: "Organização, pessoas, permissões e regras do workspace.", entity: "configuração", action: "Nova configuração", nameLabel: "Nome", detailLabel: "Valor", detailPlaceholder: "Defina o valor", statuses: ["Ativa", "Inativa"], seeds: [{ id: 1, name: "SLA sem interação", detail: "5 dias", owner: "Administrador", status: "Ativa", createdAt: "Padrão" }] },
};

export function GenericModuleWorkspace({ section }: { section: string }) {
  const config = configs[section];
  if (!config) notFound();
  const storageKey = `innovagro.module.${section}.v1`;
  const [records, setRecords] = useState<RecordItem[]>(config.seeds);
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const stored = window.localStorage.getItem(storageKey); if (stored) setRecords(JSON.parse(stored) as RecordItem[]); if (new URLSearchParams(window.location.search).has("new")) setOpen(true); } catch { window.localStorage.removeItem(storageKey); } }, [storageKey]);
  const visible = useMemo(() => { const value = query.toLowerCase().trim(); return value ? records.filter((item) => `${item.name} ${item.detail} ${item.owner} ${item.status}`.toLowerCase().includes(value)) : records; }, [query, records]);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const item: RecordItem = { id: Date.now(), name: String(form.get("name")), detail: String(form.get("detail")), owner: String(form.get("owner")), status: String(form.get("status")), createdAt: "Agora" }; setRecords((current) => { const next = [item, ...current]; window.localStorage.setItem(storageKey, JSON.stringify(next)); return next; }); setOpen(false); setSaved(true); window.setTimeout(() => setSaved(false), 2400); }
  return <div className="content"><div className="page-heading"><div><p className="eyebrow">{config.eyebrow}</p><h1 className="title">{config.title}</h1><p className="subtitle">{config.description}</p></div><button className="btn primary" onClick={() => setOpen(true)}><Plus size={16} /> {config.action}</button></div><div className="records-toolbar"><label className="search-field"><Search size={15} /><input aria-label={`Buscar ${config.entity}`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar ${config.entity}...`} /></label><span>{visible.length} {visible.length === 1 ? "registro" : "registros"}</span></div><section className="records-table panel"><div className="records-head"><span>{config.nameLabel}</span><span>{config.detailLabel}</span><span>Responsável</span><span>Status</span><span>Entrada</span></div>{visible.map((item) => <article className="records-row" key={item.id}><strong>{item.name}</strong><span>{item.detail}</span><span>{item.owner}</span><span><i className="record-status" />{item.status}</span><span className="muted">{item.createdAt}</span></article>)}{visible.length === 0 ? <div className="records-empty">Nenhum registro encontrado.</div> : null}</section>{saved ? <div className="toast"><Check size={16} /> Registro adicionado.</div> : null}{open ? <div className="modal-backdrop" onMouseDown={() => setOpen(false)}><form className="create-modal" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">NOVO REGISTRO</p><h2>{config.action}</h2></div><button type="button" className="icon-button" aria-label="Fechar" onClick={() => setOpen(false)}><X size={18} /></button></div><label className="field">{config.nameLabel}<input name="name" required autoFocus placeholder={`Informe ${config.nameLabel.toLowerCase()}`} /></label><label className="field">{config.detailLabel}<input name="detail" required placeholder={config.detailPlaceholder} /></label><div className="form-grid"><label className="field">Responsável<input name="owner" required placeholder="Nome do responsável" /></label><label className="field">Status<select name="status">{config.statuses.map((status) => <option key={status}>{status}</option>)}</select></label></div><label className="field">Próxima ação<input name="nextAction" placeholder="Descreva o próximo passo" /></label><div className="modal-actions"><button type="button" className="btn" onClick={() => setOpen(false)}>Cancelar</button><button className="btn primary">Salvar {config.entity}</button></div></form></div> : null}</div>;
}
